import * as fs from 'fs';
import * as path from 'path';
import sharp from 'sharp';
import { getArg } from '../utils/cli';

const SIZES = [320, 640, 960, 1280];
const WEBP_QUALITY = 80;
const AVIF_QUALITY = 65; // AVIF is ~20-30% smaller than WebP at similar visual quality

export interface ImageVariants {
  avif: Record<string, string>;  // e.g. "320w" → "maps-1-320.avif"
  webp: Record<string, string>;  // e.g. "320w" → "maps-1-320.webp"
  original: string;              // e.g. "maps-1.jpg"
}

export interface ImageManifest {
  [sourceName: string]: ImageVariants;
}

/**
 * Build a srcset string from variants map.
 * e.g. "/images/hero-320.webp 320w, /images/hero-640.webp 640w, ..."
 */
function buildSrcset(variants: Record<string, string>, basePath: string): string {
  return Object.entries(variants)
    .map(([size, file]) => `${basePath}/${file} ${size}`)
    .join(', ');
}

/**
 * Optimize all JPEG/PNG images in a directory.
 * Generates WebP + AVIF variants at 4 sizes for each source image.
 * Removes original JPEG/PNG after optimization to prevent deployment bloat.
 *
 * @param inputDir - directory containing source images
 * @param generateModule - if set, writes a TypeScript module at this path
 *   exporting srcset data for components to import
 * @returns image manifest mapping source names to variants
 */
export async function optimizeImages(
  inputDir: string,
  generateModule?: string,
): Promise<ImageManifest> {
  if (!fs.existsSync(inputDir)) {
    throw new Error(`Input directory not found: ${inputDir}`);
  }

  const files = fs.readdirSync(inputDir).filter((f) =>
    /\.(jpg|jpeg|png)$/i.test(f)
  );

  const manifest: ImageManifest = {};

  for (const file of files) {
    const filePath = path.join(inputDir, file);
    const baseName = path.parse(file).name;
    manifest[baseName] = { avif: {}, webp: {}, original: file };

    for (const width of SIZES) {
      // WebP variant
      const webpName = `${baseName}-${width}.webp`;
      try {
        await sharp(filePath)
          .resize(width, undefined, { withoutEnlargement: true })
          .webp({ quality: WEBP_QUALITY })
          .toFile(path.join(inputDir, webpName));
        manifest[baseName].webp[`${width}w`] = webpName;
      } catch (err) {
        console.warn(`Failed to create ${webpName}:`, (err as Error).message);
      }

      // AVIF variant
      const avifName = `${baseName}-${width}.avif`;
      try {
        await sharp(filePath)
          .resize(width, undefined, { withoutEnlargement: true })
          .avif({ quality: AVIF_QUALITY })
          .toFile(path.join(inputDir, avifName));
        manifest[baseName].avif[`${width}w`] = avifName;
      } catch (err) {
        console.warn(`Failed to create ${avifName}:`, (err as Error).message);
      }
    }

    console.log(`Optimized: ${file} → ${Object.keys(manifest[baseName].webp).length} WebP + ${Object.keys(manifest[baseName].avif).length} AVIF`);

    // Remove original JPEG/PNG — WebP/AVIF variants are sufficient.
    // Prevents Next.js static export from copying unused originals to out/.
    fs.unlinkSync(filePath);
  }

  // Generate TypeScript module for component consumption (the only consumer of image data)
  if (generateModule) {
    const imagesBasePath = '/images';
    const entries = Object.entries(manifest).map(([name, variants]) => {
      const avifSrcset = buildSrcset(variants.avif, imagesBasePath);
      const webpSrcset = buildSrcset(variants.webp, imagesBasePath);
      // Default src: largest WebP variant
      const defaultSrc = variants.webp['1280w']
        ? `${imagesBasePath}/${variants.webp['1280w']}`
        : variants.webp['960w']
          ? `${imagesBasePath}/${variants.webp['960w']}`
          : '';
      return `  ${JSON.stringify(name)}: {\n    avifSrcset: ${JSON.stringify(avifSrcset)},\n    webpSrcset: ${JSON.stringify(webpSrcset)},\n    src: ${JSON.stringify(defaultSrc)},\n  }`;
    });

    const tsModule = `// Auto-generated by optimize-images.ts — do not edit manually.
// Provides srcset data for responsive <picture> elements.

export interface ResponsiveImage {
  avifSrcset: string;
  webpSrcset: string;
  src: string;  // fallback (largest WebP)
}

export const images: Record<string, ResponsiveImage> = {
${entries.join(',\n')},
};
`;
    fs.mkdirSync(path.dirname(generateModule), { recursive: true });
    fs.writeFileSync(generateModule, tsModule);
    console.log(`TypeScript module saved to ${generateModule}`);
  }

  return manifest;
}

// CLI usage
// Standalone CLI: npx tsx packages/assets/optimize-images.ts --input path/to/images [--module path/to/images.ts]
if (require.main === module) {
  const args = process.argv.slice(2);

  if (args.includes('--help') || args.includes('-h')) {
    console.log(`Usage: npx tsx packages/assets/optimize-images.ts --input <dir> [--module <path>]

Converts all .jpg/.jpeg/.png images to responsive WebP + AVIF at 4 sizes (320, 640, 960, 1280px).
Originals are removed after conversion.

Options:
  --input <dir>     Directory containing images to optimize (REQUIRED)
  --module <path>   Generate TypeScript srcset module at this path (optional)
  --help, -h        Show this help message

Examples:
  npx tsx packages/assets/optimize-images.ts --input output/my-site/public/images
  npx tsx packages/assets/optimize-images.ts --input ./scraped-images --module ./src/data/images.ts`);
    process.exit(0);
  }

  const inputDir = getArg(args, 'input', '');
  if (!inputDir) {
    console.error('Error: --input is required. Use --help for usage info.');
    process.exit(1);
  }

  const tsModule = getArg(args, 'module', '');

  optimizeImages(inputDir, tsModule || undefined)
    .then((manifest) =>
      console.log(`\nProcessed ${Object.keys(manifest).length} images`)
    )
    .catch((err) => {
      console.error('Error:', err.message);
      process.exit(1);
    });
}
